name: GitHub Actions Runner in Docker - Base
on:
  push:
    paths: [Dockerfile.base]
    branches:
      - master
      - develop
  schedule: [cron: "0 22 * * *"]

jobs:
  ubuntu_base_latest_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ORG}/github-runner-base:latest
          platforms: linux/amd64,linux/arm64,linux/386
          file: ./Dockerfile.base

  ubuntu_base_bionic_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Copy Dockerfile
        run: cp Dockerfile.base Dockerfile.base.ubuntu-bionic; sed -i.bak 's/FROM.*/FROM ubuntu:bionic/' Dockerfile.base.ubuntu-bionic
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ORG}/github-runner-base:ubuntu-bionic
          platforms: linux/amd64,linux/arm64,linux/386
          file: ./Dockerfile.base.ubuntu-bionic

  ubuntu_base_xenial_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Copy Dockerfile
        run: cp Dockerfile.base Dockerfile.base.ubuntu-xenial; sed -i.bak 's/FROM.*/FROM ubuntu:xenial/' Dockerfile.base.ubuntu-xenial
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ORG}/github-runner-base:ubuntu-xenial
          platforms: linux/amd64,linux/arm64,linux/386
          file: ./Dockerfile.base.ubuntu-xenial
