name: Publish Docker
on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master

     #This Action Emits 2 Variables, IMAGE_SHA_NAME and IMAGE_URL 
     #which you can reference in subsequent steps
    - name: Publish Docker Image to GPR
      uses: myoung34/gpr-docker-publish@master
      id: docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        IMAGE_NAME: 'runner'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
