name: GitHub Actions Runner in Docker - Latest
on:
  push:
    paths-ignore:
      - Dockerfile.base
      - README.md
    branches:
      - master
      - develop
  schedule:
    - cron: "59 23 * * *"

jobs:
  ubuntu_latest_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ORG}/github-runner:latest
          platforms: linux/amd64,linux/arm64,linux/386
          file: ./Dockerfile

  ubuntu_bionic_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Copy Dockerfile
        run: cp Dockerfile Dockerfile.ubuntu-bionic; sed -i.bak "s/FROM.*/FROM ${ORG}\/github-runner-base:ubuntu-bionic/" Dockerfile.ubuntu-bionic
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ORG}/github-runner:latest
          platforms: linux/amd64,linux/arm64,linux/386
          file: ./Dockerfile.ubuntu-bionic

  ubuntu_xenial_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Copy Dockerfile
        run: cp Dockerfile Dockerfile.ubuntu-xenial; sed -i.bak "s/FROM.*/FROM ${ORG}\/github-runner-base:ubuntu-xenial/" Dockerfile.ubuntu-xenial
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ORG}/github-runner:latest
          platforms: linux/amd64,linux/arm64,linux/386
          file: ./Dockerfile.ubuntu-xenial
