name: Publish Docker
on:
  push:
    tags:
      - '*'

jobs:
  release_x86:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Publish to Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myoung34/github-runner
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        tag_names: true
  release_arm:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.arm -t myoung34/github-runner:${TAG}-arm .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-arm
