name: Publish Docker
on:
  push:
    tags:
      - '*'

jobs:
  ubuntu_tag_deploy_x86:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu -t myoung34/github-runner:${TAG} .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}
  ubuntu_bionic_deploy_x86:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-bionic -t myoung34/github-runner:${TAG}-ubuntu-bionic .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-ubuntu-bionic
  ubuntu_xenial_deploy_x86:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-xenial -t myoung34/github-runner:${TAG}-ubuntu-xenial .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-ubuntu-xenial
  ubuntu_tag_deploy_arm:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-arm -t myoung34/github-runner:${TAG}-arm .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-arm
  ubuntu_bionic_deploy_arm:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-bionic-arm -t myoung34/github-runner:${TAG}-ubuntu-bionic-arm .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-ubuntu-bionic-arm
  ubuntu_xenial_deploy_arm:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-xenial-arm -t myoung34/github-runner:${TAG}-ubuntu-xenial-arm .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-ubuntu-xenial-arm
  ubuntu_tag_deploy_arm64:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-arm -t myoung34/github-runner:${TAG}-arm64 --build-arg DOCKER_ARCH=arm64 --build-arg ACTIONS_ARCH=arm64 .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-arm64
  ubuntu_bionic_deploy_arm64:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-bionic-arm -t myoung34/github-runner:${TAG}-ubuntu-bionic-arm64 --build-arg DOCKER_ARCH=arm64 --build-arg ACTIONS_ARCH=arm64 .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-ubuntu-bionic-arm64
  ubuntu_xenial_deploy_arm64:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Build
      run: docker build -f Dockerfile.ubuntu-xenial-arm -t myoung34/github-runner:${TAG}-ubuntu-xenial-arm64 --build-arg DOCKER_ARCH=arm64 --build-arg ACTIONS_ARCH=arm64 .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Push to hub registry
      run: docker push myoung34/github-runner:${TAG}-ubuntu-xenial-arm64
